POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Evento nodejs",
  "details": null,
  "maximumAttendees": 80
}

###
POST http://localhost:3333/events/87819056-36a9-4885-aa07-08b45fa9cbdb/attendees
Content-Type: application/json

{
  "name": "Rodrigo gonçalves",
  "email": "rodrigo@rocketseat.com.br"
}

###
GET http://localhost:3333/events/6c4eb8c8-43e4-42c9-91fb-3a2b9da590d3

###
GET http://localhost:3333/attendees/2/badge

###
GET http://localhost:3333/attendees/4/check-in

###
GET http://localhost:3333/events/87819056-36a9-4885-aa07-08b45fa9cbdb/attendees